@api = https://jsonplaceholder.typicode.com 

### Obteniendo todas las publicaciones
{{api}}/posts

### Obteniendo una sola publicación
GET {{api}}/posts/1

### Creando una nueva publicación
POST {{api}}/posts
Content-Type: application/json

{
    "title": "vs code",
    "body": "Cuerpo del mensaje"
}

### Eliminando publicación
DELETE {{api}}/posts/1

### Actualizar publicación por id
PUT {{api}}/posts/1
Content-Type: application/json

{
    "title": "Actualización",
    "body": "Actualizando bloque de código"
}

// ----------------------------------------- Rest Client ---------------------------------------------->>
@apiRest = http://localhost:8080

### Creando cliente
POST {{apiRest}}/auth/register
Content-Type: application/json

{
    "id" : 1,
    "label" : "Cliente",
    "cedula" : "567567",
    "imagenPerfil" : "urlImagen",
    "nombreCompleto" : "Felipe Hernandez",
    "email": "Felipe@gmail.com",
    "contrasena" : "1234567",
    "membresia" : 1,
    "estado" : 1
}

### Autenticación
GET {{apiRest}}/auth/login/felipe@gmail.com/1234567
Content-Type: application/json

{
    "email": "felipe@gmail.com",
    "contrasena" : "1234567",
}

### Autenticación administrador
GET {{apiRest}}/auth/login/admin2@gmail.com/123
Content-Type: application/json
Accept: application/json
Authorization: Basic YWRtaW4yQGdtYWlsLmNvbToxMjM=


### Autenticación administrador teatro
GET {{apiRest}}/auth/login/admin2@gmail.com/123
Content-Type: application/json

{
    "email": "admin2@gmail.com",
    "contrasena" : "123",
}

### Autenticación
GET {{apiRest}}/auth
Content-Type: application/json

{
    "email": "asfas@sdfasf.com",
    "contrasena" : "sfdasfdasf",
}

### Obtener ciudad
GET {{apiRest}}/obtener-ciudad/1

###
GET {{apiRest}}/detalle-usuarios

### Obtener usuario por cédula
GET {{apiRest}}/detalle-usuario/2432343425

### Eliminar usuario
DELETE {{apiRest}}/delete/kjhlkjhlkhlk

### Actualizar usuario
PUT {{apiRest}}/update
Content-Type: application/json

{
    "cedula" : "12345",
    "id" : 1,
    "label" : "Cliente",
    "imagenPerfil" : "urlImagen",
    "nombreCompleto" : "Juan Sebastian",
    "email": "JuanS@gmail.com",
    "contrasena" : "1234567"
}

###
PUT {{apiRest}}/update
Content-Type: application/json

{
    "id" : 1,
    "label" : "Cliente",
    "cedula" : "12347",
    "imagenPerfil" : "urlImagen",
    "nombreCompleto" : "Sara Hernandez",
    "email": "Sarha@gmail.com",
    "contrasena" : "1234567",
    "membresia" : false,
    "estado" : false
}



// --------------------------------------------------------------------------------------------------\\

// ----------------------------------------- Rest Administrator ---------------------------------------------->>
### Obtener la lista de la confiteria
GET {{apiRest}}/lista-confiteria

### Lista Peliculas
GET {{apiRest}}/lista-peliculas
Authorization: Bearer $2a$10$kCgF9Jo78qisrRePG58Hx..RxWhHEHQXtN0qRcg0JtGPVWZSPXJIq

### Creando pelicula
POST {{apiRest}}/crear-pelicula
Content-Type: application/json

{
    "idPelicula": 0,
    "nombre" : "Titanic",
    "imagen" : "UrlImgen",
    "trailer" : "Trailer",
    "genero" : "Comedia",
    "sinopsis" : "BALABAL",
    "reparto" : "dos",
    "estadoPelicula" : "CARTELERA"
}

### Actualizar película
PUT {{apiRest}}/actualizar-pelicula
Content-Type: application/json

{
    "idPelicula": 1,
    "nombre" : "Titanic",
    "imagen" : "UrlImgen",
    "trailer" : "Trailer",
    "genero" : "Comedia",
    "sinopsis" : "Barco",
    "reparto" : "dos",
    "estadoPelicula" : "PREVENTA"
}

### Obtener pelicula
GET {{apiRest}}/detalle-pelicula/2

### Eliminar pelicula
DELETE {{apiRest}}/eliminar-pelicula/2

### Lista Teatros
GET {{apiRest}}/lista-teatros

### Lista Confiterías
GET {{apiRest}}/lista-confiteria


### Obtener la lista de los cupones
GET {{apiRest}}/lista-cupones



// --------------------------------------------------------------------------------------------------\\

// ----------------------------------------- Rest Administrator Teatro ---------------------------------------------->>
### Obtener la lista de los horarios
GET {{apiRest}}/lista-horarios

### Obtener la lista de las salas
GET {{apiRest}}/lista-salas




// ------------------------------------------------------------------------------------------------------------------\\