
import 'package:uni_cine/ui/views/unicine/room_unicine/chair.dart';

class TypeInitChars {

  static List<Chair> initChairs() {

    List<Chair> chairs;
  
    chairs = [

        

      Chair(column: 1, row: 'A', status: 0),Chair(column: 2, row: 'A', status: 0),Chair(column: 3, row: 'A', status: 1),Chair(column: 4, row: 'A', status: 1),Chair(column: 0, row: 'A', status: 'A'),Chair(column: 5, row: 'A', status: 1), Chair(column: 6, row: 'A', status: 1), Chair(column: 7, row: 'A', status: 1), Chair(column: 8, row: 'A', status: 1), Chair(column: 9, row: 'A', status: 1), Chair(column: 10, row: 'A', status: 1), Chair(column: 0, row: 'A', status: 0), Chair(column: 11, row: 'A', status: 1), Chair(column: 12, row: 'A', status: 1), Chair(column: 13, row: 'A', status: 1), Chair(column: 14, row: 'A', status: 1), Chair(column: 15, row: 'A', status: 1), Chair(column: 16, row: 'A', status: 1), Chair(column: 0, row: 'A', status: 'A'), Chair(column: 17, row: 'A', status: 1), Chair(column:18, row: 'A', status: 1), Chair(column: 19, row: 'A', status: 0), Chair(column: 20, row: 'A', status: 0),
      Chair(column: 1, row: 'B', status: 1),Chair(column: 2, row: 'B', status: 1),Chair(column: 3, row: 'B', status: 1),Chair(column: 4, row: 'B', status: 1),Chair(column: 0, row: 'B', status: 'B'),Chair(column: 5, row: 'B', status: 1), Chair(column: 6, row: 'B', status: 1), Chair(column: 7, row: 'B', status: 1), Chair(column: 8, row: 'B', status: 1), Chair(column: 9, row: 'B', status: 1), Chair(column: 10, row: 'B', status: 1), Chair(column: 0, row: 'B', status: 0), Chair(column: 11, row: 'B', status: 1), Chair(column: 12, row: 'B', status: 1), Chair(column: 13, row: 'B', status: 1), Chair(column: 14, row: 'B', status: 1), Chair(column: 15, row: 'B', status: 1), Chair(column: 16, row: 'B', status: 1), Chair(column: 0, row: 'B', status: 'B'), Chair(column: 17, row: 'B', status: 1), Chair(column:18, row: 'B', status: 1), Chair(column: 19, row: 'B', status: 1), Chair(column: 20, row: 'B', status: 1),
      Chair(column: 1, row: 'C', status: 1),Chair(column: 2, row: 'C', status: 1),Chair(column: 3, row: 'C', status: 1),Chair(column: 4, row: 'C', status: 1),Chair(column: 0, row: 'C', status: 'C'),Chair(column: 5, row: 'C', status: 1), Chair(column: 6, row: 'C', status: 1), Chair(column: 7, row: 'C', status: 1), Chair(column: 8, row: 'C', status: 1), Chair(column: 9, row: 'C', status: 1), Chair(column: 10, row: 'C', status: 1), Chair(column: 0, row: 'C', status: 0), Chair(column: 11, row: 'C', status: 1), Chair(column: 12, row: 'C', status: 1), Chair(column: 13, row: 'C', status: 1), Chair(column: 14, row: 'C', status: 1), Chair(column: 15, row: 'C', status: 1), Chair(column: 16, row: 'C', status: 1), Chair(column: 0, row: 'C', status: 'C'), Chair(column: 17, row: 'C', status: 1), Chair(column:18, row: 'C', status: 1), Chair(column: 19, row: 'C', status: 1), Chair(column: 20, row: 'C', status: 1),
      Chair(column: 1, row: 'D', status: 1),Chair(column: 2, row: 'D', status: 1),Chair(column: 3, row: 'D', status: 1),Chair(column: 4, row: 'D', status: 1),Chair(column: 0, row: 'D', status: 'D'),Chair(column: 5, row: 'D', status: 1), Chair(column: 6, row: 'D', status: 1), Chair(column: 7, row: 'D', status: 1), Chair(column: 8, row: 'D', status: 1), Chair(column: 9, row: 'D', status: 1), Chair(column: 10, row: 'D', status: 1), Chair(column: 0, row: 'D', status: 0), Chair(column: 11, row: 'D', status: 1), Chair(column: 12, row: 'D', status: 1), Chair(column: 13, row: 'D', status: 1), Chair(column: 14, row: 'D', status: 1), Chair(column: 15, row: 'D', status: 1), Chair(column: 16, row: 'D', status: 1), Chair(column: 0, row: 'D', status: 'D'), Chair(column: 17, row: 'D', status: 1), Chair(column:18, row: 'D', status: 1), Chair(column: 19, row: 'D', status: 1), Chair(column: 20, row: 'D', status: 1),
      Chair(column: 1, row: 'E', status: 1),Chair(column: 2, row: 'E', status: 1),Chair(column: 3, row: 'E', status: 1),Chair(column: 4, row: 'E', status: 1),Chair(column: 0, row: 'E', status: 'E'),Chair(column: 5, row: 'E', status: 1), Chair(column: 6, row: 'E', status: 1), Chair(column: 7, row: 'E', status: 1), Chair(column: 8, row: 'E', status: 1), Chair(column: 9, row: 'E', status: 1), Chair(column: 10, row: 'E', status: 1), Chair(column: 0, row: 'E', status: 0), Chair(column: 11, row: 'E', status: 1), Chair(column: 12, row: 'E', status: 1), Chair(column: 13, row: 'E', status: 1), Chair(column: 14, row: 'E', status: 1), Chair(column: 15, row: 'E', status: 1), Chair(column: 16, row: 'E', status: 1), Chair(column: 0, row: 'E', status: 'E'), Chair(column: 17, row: 'E', status: 1), Chair(column:18, row: 'E', status: 1), Chair(column: 19, row: 'E', status: 1), Chair(column: 20, row: 'E', status: 1),
      Chair(column: 1, row: 'F', status: 1),Chair(column: 2, row: 'F', status: 1),Chair(column: 3, row: 'F', status: 1),Chair(column: 4, row: 'F', status: 1),Chair(column: 0, row: 'F', status: 'F'),Chair(column: 5, row: 'F', status: 1), Chair(column: 6, row: 'F', status: 1), Chair(column: 7, row: 'F', status: 1), Chair(column: 8, row: 'F', status: 1), Chair(column: 9, row: 'F', status: 1), Chair(column: 10, row: 'F', status: 1), Chair(column: 0, row: 'F', status: 0), Chair(column: 11, row: 'F', status: 1), Chair(column: 12, row: 'F', status: 1), Chair(column: 13, row: 'F', status: 1), Chair(column: 14, row: 'F', status: 1), Chair(column: 15, row: 'F', status: 1), Chair(column: 16, row: 'F', status: 1), Chair(column: 0, row: 'F', status: 'F'), Chair(column: 17, row: 'F', status: 1), Chair(column:18, row: 'F', status: 1), Chair(column: 19, row: 'F', status: 1), Chair(column: 20, row: 'F', status: 1),
      Chair(column: 1, row: '0', status: 0),Chair(column: 2, row: '0', status: 0),Chair(column: 3, row: '0', status: 0),Chair(column: 4, row: '0', status: 0),Chair(column: 0, row: '0', status:  0),Chair(column: 5, row: '0', status: 0), Chair(column: 6, row: '0', status: 0), Chair(column: 7, row: '0', status: 0), Chair(column: 8, row: '0', status: 0), Chair(column: 9, row: '0', status: 0), Chair(column: 10, row: '0', status: 0), Chair(column: 0, row: '0', status: 0), Chair(column: 11, row: '0', status: 0), Chair(column: 12, row: '0', status: 0), Chair(column: 13, row: '0', status: 0), Chair(column: 14, row: '0', status: 0), Chair(column: 15, row: '0', status: 0), Chair(column: 16, row: '0', status: 0), Chair(column: 0, row: '0', status: 0), Chair(column: 17, row: '0', status: 0), Chair(column:18, row: '0', status: 0), Chair(column: 19, row: '0', status: 0), Chair(column: 20, row: '0', status: 0),
      Chair(column: 1, row: 'G', status: 1),Chair(column: 2, row: 'G', status: 1),Chair(column: 3, row: 'G', status: 1),Chair(column: 4, row: 'G', status: 1),Chair(column: 0, row: 'G', status: 'G'),Chair(column: 5, row: 'G', status: 1), Chair(column: 6, row: 'G', status: 1), Chair(column: 7, row: 'G', status: 1), Chair(column: 8, row: 'G', status: 1), Chair(column: 9, row: 'G', status: 1), Chair(column: 10, row: 'G', status: 1), Chair(column: 0, row: 'G', status: 0), Chair(column: 11, row: 'G', status: 1), Chair(column: 12, row: 'G', status: 1), Chair(column: 13, row: 'G', status: 1), Chair(column: 14, row: 'G', status: 1), Chair(column: 15, row: 'G', status: 1), Chair(column: 16, row: 'G', status: 1), Chair(column: 0, row: 'G', status: 'G'), Chair(column: 17, row: 'G', status: 1), Chair(column:18, row: 'G', status: 1), Chair(column: 19, row: 'G', status: 1), Chair(column: 20, row: 'G', status: 1),
      Chair(column: 1, row: 'H', status: 1),Chair(column: 2, row: 'H', status: 1),Chair(column: 3, row: 'H', status: 1),Chair(column: 4, row: 'H', status: 1),Chair(column: 0, row: 'H', status: 'H'),Chair(column: 5, row: 'H', status: 1), Chair(column: 6, row: 'H', status: 1), Chair(column: 7, row: 'H', status: 1), Chair(column: 8, row: 'H', status: 1), Chair(column: 9, row: 'H', status: 1), Chair(column: 10, row: 'H', status: 1), Chair(column: 0, row: 'H', status: 0), Chair(column: 11, row: 'H', status: 1), Chair(column: 12, row: 'H', status: 1), Chair(column: 13, row: 'H', status: 1), Chair(column: 14, row: 'H', status: 1), Chair(column: 15, row: 'H', status: 1), Chair(column: 16, row: 'H', status: 1), Chair(column: 0, row: 'H', status: 'H'), Chair(column: 17, row: 'H', status: 1), Chair(column:18, row: 'H', status: 1), Chair(column: 19, row: 'H', status: 1), Chair(column: 20, row: 'H', status: 1),
      Chair(column: 1, row: 'I', status: 1),Chair(column: 2, row: 'I', status: 1),Chair(column: 3, row: 'I', status: 1),Chair(column: 4, row: 'I', status: 1),Chair(column: 0, row: 'I', status: 'I'),Chair(column: 5, row: 'I', status: 1), Chair(column: 6, row: 'I', status: 1), Chair(column: 7, row: 'I', status: 1), Chair(column: 8, row: 'I', status: 1), Chair(column: 9, row: 'I', status: 1), Chair(column: 10, row: 'I', status: 1), Chair(column: 0, row: 'I', status: 0), Chair(column: 11, row: 'I', status: 1), Chair(column: 12, row: 'I', status: 1), Chair(column: 13, row: 'I', status: 1), Chair(column: 14, row: 'I', status: 1), Chair(column: 15, row: 'I', status: 1), Chair(column: 16, row: 'I', status: 1), Chair(column: 0, row: 'I', status: 'I'), Chair(column: 17, row: 'I', status: 1), Chair(column:18, row: 'I', status: 1), Chair(column: 19, row: 'I', status: 1), Chair(column: 20, row: 'I', status: 1),
      Chair(column: 1, row: 'J', status: 1),Chair(column: 2, row: 'J', status: 1),Chair(column: 3, row: 'J', status: 1),Chair(column: 4, row: 'J', status: 1),Chair(column: 0, row: 'J', status: 'J'),Chair(column: 5, row: 'J', status: 1), Chair(column: 6, row: 'J', status: 1), Chair(column: 7, row: 'J', status: 1), Chair(column: 8, row: 'J', status: 1), Chair(column: 9, row: 'J', status: 1), Chair(column: 10, row: 'J', status: 1), Chair(column: 0, row: 'J', status: 0), Chair(column: 11, row: 'J', status: 1), Chair(column: 12, row: 'J', status: 1), Chair(column: 13, row: 'J', status: 1), Chair(column: 14, row: 'J', status: 1), Chair(column: 15, row: 'J', status: 1), Chair(column: 16, row: 'J', status: 1), Chair(column: 0, row: 'J', status: 'J'), Chair(column: 17, row: 'J', status: 1), Chair(column:18, row: 'J', status: 1), Chair(column: 19, row: 'J', status: 1), Chair(column: 20, row: 'J', status: 1),
      Chair(column: 1, row: 'K', status: 1),Chair(column: 2, row: 'K', status: 1),Chair(column: 3, row: 'K', status: 1),Chair(column: 4, row: 'K', status: 1),Chair(column: 0, row: 'K', status: 'K'),Chair(column: 5, row: 'K', status: 1), Chair(column: 6, row: 'K', status: 1), Chair(column: 7, row: 'K', status: 1), Chair(column: 8, row: 'K', status: 1), Chair(column: 9, row: 'K', status: 1), Chair(column: 10, row: 'K', status: 1), Chair(column: 0, row: 'K', status: 0), Chair(column: 11, row: 'K', status: 1), Chair(column: 12, row: 'K', status: 1), Chair(column: 13, row: 'K', status: 1), Chair(column: 14, row: 'K', status: 1), Chair(column: 15, row: 'K', status: 1), Chair(column: 16, row: 'K', status: 1), Chair(column: 0, row: 'K', status: 'K'), Chair(column: 17, row: 'K', status: 1), Chair(column:18, row: 'K', status: 1), Chair(column: 19, row: 'K', status: 1), Chair(column: 20, row: 'K', status: 1),
      Chair(column: 1, row: 'L', status: 1),Chair(column: 2, row: 'L', status: 1),Chair(column: 3, row: 'L', status: 1),Chair(column: 4, row: 'L', status: 1),Chair(column: 0, row: 'L', status: 'L'),Chair(column: 5, row: 'L', status: 1), Chair(column: 6, row: 'L', status: 1), Chair(column: 7, row: 'L', status: 1), Chair(column: 8, row: 'L', status: 1), Chair(column: 9, row: 'L', status: 1), Chair(column: 10, row: 'L', status: 1), Chair(column: 0, row: 'L', status: 0), Chair(column: 11, row: 'L', status: 1), Chair(column: 12, row: 'L', status: 1), Chair(column: 13, row: 'L', status: 1), Chair(column: 14, row: 'L', status: 1), Chair(column: 15, row: 'L', status: 1), Chair(column: 16, row: 'L', status: 1), Chair(column: 0, row: 'L', status: 'L'), Chair(column: 17, row: 'L', status: 1), Chair(column:18, row: 'L', status: 1), Chair(column: 19, row: 'L', status: 1), Chair(column: 20, row: 'L', status: 1),
      Chair(column: 1, row: '0', status:'1'),Chair(column: 2, row: '0', status:'2'),Chair(column: 3, row: '0', status: '3'),Chair(column: 4, row: '0', status: 4),Chair(column: 0, row: '0', status: 0),Chair(column: 5, row: '0', status: 5), Chair(column: 6, row: '0', status: 6), Chair(column: 7, row: '0', status: 7), Chair(column: 8, row: '0', status: 8), Chair(column: 9, row: '0', status: 9), Chair(column: 10, row: '0', status:10), Chair(column: 0, row: '0', status: 0), Chair(column: 11, row: '0', status:11), Chair(column: 12, row: '0', status: 12), Chair(column: 13, row: '0', status: 13), Chair(column: 14, row: '0', status: 14), Chair(column: 15, row: '0', status: 15), Chair(column: 16, row: '0', status: 16), Chair(column: 0, row: '0', status: 0), Chair(column: 17, row: '0', status: 17), Chair(column:18, row: '0', status: 18), Chair(column: 19, row: '0', status: 19), Chair(column: 20, row: '0', status: 20),



    //   0, 0, 1, 1, 'A', 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 'A', 1, 1, 0, 0,
    //   1, 1, 1, 1, 'B', 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 'B', 1, 1, 1, 1,
    //   1, 1, 1, 1, 'C', 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 'C', 1, 1, 1, 1,
    //   1, 1, 1, 1, 'D', 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 'D', 1, 1, 1, 1,
    //   1, 1, 1, 1, 'E', 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 'E', 1, 1, 1, 1,
    //   1, 1, 1, 1, 'F', 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 'F', 1, 1, 1, 1,
    //   0, 0, 0, 0,  0 , 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  0,  0, 0, 0, 0,
    //   1, 1, 1, 1, 'G', 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 'G', 1, 1, 1, 1,
    //   1, 1, 1, 1, 'H', 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 'H', 1, 1, 1, 1,
    //   1, 1, 1, 1, 'I', 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 'I', 1, 1, 1, 1,
    //   1, 1, 1, 1, 'J', 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 'J', 1, 1, 1, 1,
    //   1, 1, 1, 1, 'K', 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 'K', 1, 1, 1, 1,
    //   1, 1, 1, 1, 'L', 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 'L', 1, 1, 1, 1,
    // '1', 2, 3, 4,   0, 5, 6, 7, 8, 9,10, 0,11,12,13,14,15,16,   0,17,18,19,20
    ];

    return chairs;
  }

  static List<Chair> type2() {

    List<Chair> chairs;
  
    chairs = [

      Chair(column: 1, row: 'A', status: 0),  Chair(column: 2, row: 'A', status: 0),  Chair(column: 3, row: 'A', status: 1),  Chair(column: 4, row: 'A', status: 1), Chair(column: 5, row: 'A', status: 1), Chair(column: 6, row: 'A', status: 1), Chair(column: 0, row: 'A', status: 'A'), Chair(column: 7, row: 'A', status: 1), Chair(column: 8, row: 'A', status: 1), Chair(column: 9, row: 'A', status: 1), Chair(column: 10, row: 'A', status: 1), Chair(column: 11, row: 'A', status: 1),Chair(column: 12, row: 'A', status: 1), Chair(column: 13, row: 'A', status: 1), Chair(column: 14, row: 'A', status: 1), Chair(column: 15, row: 'A', status: 1),Chair(column: 16, row: 'A', status: 1),Chair(column: 17, row: 'A', status: 1),Chair(column: 18, row: 'A', status: 1),Chair(column: 19, row: 'A', status: 1),Chair(column: 20, row: 'A', status: 1),Chair(column: 21, row: 'A', status: 1),Chair(column: 22, row: 'A', status: 1),Chair(column: 23, row: 'A', status: 1),Chair(column: 24, row: 'A', status: 1),Chair(column: 25, row: 'A', status: 1), Chair(column: 0, row: 'A', status: 'A'),Chair(column: 26, row: 'A', status: 1), Chair(column: 27, row: 'A', status: 1), Chair(column: 28, row: 'A', status: 1), Chair(column: 29, row: 'A', status: 1), Chair(column: 30, row: 'A', status: 0), Chair(column: 31, row: 'A', status: 0),
      Chair(column: 1, row: 'B', status: 1),  Chair(column: 2, row: 'B', status: 1),  Chair(column: 3, row: 'B', status: 1),  Chair(column: 4, row: 'B', status: 1), Chair(column: 5, row: 'B', status: 1), Chair(column: 6, row: 'B', status: 1), Chair(column: 0, row: 'B', status: 'B'), Chair(column: 7, row: 'B', status: 1), Chair(column: 8, row: 'B', status: 1), Chair(column: 9, row: 'B', status: 1), Chair(column: 10, row: 'B', status: 1), Chair(column: 11, row: 'B', status: 1),Chair(column: 12, row: 'B', status: 1), Chair(column: 13, row: 'B', status: 1), Chair(column: 14, row: 'B', status: 1), Chair(column: 15, row: 'B', status: 1),Chair(column: 16, row: 'B', status: 1),Chair(column: 17, row: 'B', status: 1),Chair(column: 18, row: 'B', status: 1),Chair(column: 19, row: 'B', status: 1),Chair(column: 20, row: 'B', status: 1),Chair(column: 21, row: 'B', status: 1),Chair(column: 22, row: 'B', status: 1),Chair(column: 23, row: 'B', status: 1),Chair(column: 24, row: 'B', status: 1),Chair(column: 25, row: 'B', status: 1), Chair(column: 0, row: 'B', status: 'B'),Chair(column: 26, row: 'B', status: 1), Chair(column: 27, row: 'B', status: 1), Chair(column: 28, row: 'B', status: 1), Chair(column: 29, row: 'B', status: 1), Chair(column: 30, row: 'B', status: 1), Chair(column: 31, row: 'B', status: 1),
      Chair(column: 1, row: 'C', status: 1),  Chair(column: 2, row: 'C', status: 1),  Chair(column: 3, row: 'C', status: 1),  Chair(column: 4, row: 'C', status: 1), Chair(column: 5, row: 'C', status: 1), Chair(column: 6, row: 'C', status: 1), Chair(column: 0, row: 'C', status: 'C'), Chair(column: 7, row: 'C', status: 1), Chair(column: 8, row: 'C', status: 1), Chair(column: 9, row: 'C', status: 1), Chair(column: 10, row: 'C', status: 1), Chair(column: 11, row: 'C', status: 1),Chair(column: 12, row: 'C', status: 1), Chair(column: 13, row: 'C', status: 1), Chair(column: 14, row: 'C', status: 1), Chair(column: 15, row: 'C', status: 1),Chair(column: 16, row: 'C', status: 1),Chair(column: 17, row: 'C', status: 1),Chair(column: 18, row: 'C', status: 1),Chair(column: 19, row: 'C', status: 1),Chair(column: 20, row: 'C', status: 1),Chair(column: 21, row: 'C', status: 1),Chair(column: 22, row: 'C', status: 1),Chair(column: 23, row: 'C', status: 1),Chair(column: 24, row: 'C', status: 1),Chair(column: 25, row: 'C', status: 1), Chair(column: 0, row: 'C', status: 'C'),Chair(column: 26, row: 'C', status: 1), Chair(column: 27, row: 'C', status: 1), Chair(column: 28, row: 'C', status: 1), Chair(column: 29, row: 'C', status: 1), Chair(column: 30, row: 'C', status: 1), Chair(column: 31, row: 'C', status: 1),
      Chair(column: 1, row: 'D', status: 1),  Chair(column: 2, row: 'D', status: 1),  Chair(column: 3, row: 'D', status: 1),  Chair(column: 4, row: 'D', status: 1), Chair(column: 5, row: 'D', status: 1), Chair(column: 6, row: 'D', status: 1), Chair(column: 0, row: 'D', status: 'D'), Chair(column: 7, row: 'D', status: 1), Chair(column: 8, row: 'D', status: 1), Chair(column: 9, row: 'D', status: 1), Chair(column: 10, row: 'D', status: 1), Chair(column: 11, row: 'D', status: 1),Chair(column: 12, row: 'D', status: 1), Chair(column: 13, row: 'D', status: 1), Chair(column: 14, row: 'D', status: 1), Chair(column: 15, row: 'D', status: 1),Chair(column: 16, row: 'D', status: 1),Chair(column: 17, row: 'D', status: 1),Chair(column: 18, row: 'D', status: 1),Chair(column: 19, row: 'D', status: 1),Chair(column: 20, row: 'D', status: 1),Chair(column: 21, row: 'D', status: 1),Chair(column: 22, row: 'D', status: 1),Chair(column: 23, row: 'D', status: 1),Chair(column: 24, row: 'D', status: 1),Chair(column: 25, row: 'D', status: 1), Chair(column: 0, row: 'D', status: 'D'),Chair(column: 26, row: 'D', status: 1), Chair(column: 27, row: 'D', status: 1), Chair(column: 28, row: 'D', status: 1), Chair(column: 29, row: 'D', status: 1), Chair(column: 30, row: 'D', status: 1), Chair(column: 31, row: 'D', status: 1),
      Chair(column: 1, row: 'E', status: 1),  Chair(column: 2, row: 'E', status: 1),  Chair(column: 3, row: 'E', status: 1),  Chair(column: 4, row: 'E', status: 1), Chair(column: 5, row: 'E', status: 1), Chair(column: 6, row: 'E', status: 1), Chair(column: 0, row: 'E', status: 'E'), Chair(column: 7, row: 'E', status: 1), Chair(column: 8, row: 'E', status: 1), Chair(column: 9, row: 'E', status: 1), Chair(column: 10, row: 'E', status: 1), Chair(column: 11, row: 'E', status: 1),Chair(column: 12, row: 'E', status: 1), Chair(column: 13, row: 'E', status: 1), Chair(column: 14, row: 'E', status: 1), Chair(column: 15, row: 'E', status: 1),Chair(column: 16, row: 'E', status: 1),Chair(column: 17, row: 'E', status: 1),Chair(column: 18, row: 'E', status: 1),Chair(column: 19, row: 'E', status: 1),Chair(column: 20, row: 'E', status: 1),Chair(column: 21, row: 'E', status: 1),Chair(column: 22, row: 'E', status: 1),Chair(column: 23, row: 'E', status: 1),Chair(column: 24, row: 'E', status: 1),Chair(column: 25, row: 'E', status: 1), Chair(column: 0, row: 'E', status: 'E'),Chair(column: 26, row: 'E', status: 1), Chair(column: 27, row: 'E', status: 1), Chair(column: 28, row: 'E', status: 1), Chair(column: 29, row: 'E', status: 1), Chair(column: 30, row: 'E', status: 1), Chair(column: 31, row: 'E', status: 1),
      Chair(column: 1, row: 'F', status: 1),  Chair(column: 2, row: 'F', status: 1),  Chair(column: 3, row: 'F', status: 1),  Chair(column: 4, row: 'F', status: 1), Chair(column: 5, row: 'F', status: 1), Chair(column: 6, row: 'F', status: 1), Chair(column: 0, row: 'F', status: 'F'), Chair(column: 7, row: 'F', status: 1), Chair(column: 8, row: 'F', status: 1), Chair(column: 9, row: 'F', status: 1), Chair(column: 10, row: 'F', status: 1), Chair(column: 11, row: 'F', status: 1),Chair(column: 12, row: 'F', status: 1), Chair(column: 13, row: 'F', status: 1), Chair(column: 14, row: 'F', status: 1), Chair(column: 15, row: 'F', status: 1),Chair(column: 16, row: 'F', status: 1),Chair(column: 17, row: 'F', status: 1),Chair(column: 18, row: 'F', status: 1),Chair(column: 19, row: 'F', status: 1),Chair(column: 20, row: 'F', status: 1),Chair(column: 21, row: 'F', status: 1),Chair(column: 22, row: 'F', status: 1),Chair(column: 23, row: 'F', status: 1),Chair(column: 24, row: 'F', status: 1),Chair(column: 25, row: 'F', status: 1), Chair(column: 0, row: 'F', status: 'F'),Chair(column: 26, row: 'F', status: 1), Chair(column: 27, row: 'F', status: 1), Chair(column: 28, row: 'F', status: 1), Chair(column: 29, row: 'F', status: 1), Chair(column: 30, row: 'F', status: 1), Chair(column: 31, row: 'F', status: 1),
      Chair(column: 1, row: 'G', status: 1),  Chair(column: 2, row: 'G', status: 1),  Chair(column: 3, row: 'G', status: 1),  Chair(column: 4, row: 'G', status: 1), Chair(column: 5, row: 'G', status: 1), Chair(column: 6, row: 'G', status: 1), Chair(column: 0, row: 'G', status: 'G'), Chair(column: 7, row: 'G', status: 1), Chair(column: 8, row: 'G', status: 1), Chair(column: 9, row: 'G', status: 1), Chair(column: 10, row: 'G', status: 1), Chair(column: 11, row: 'G', status: 1),Chair(column: 12, row: 'G', status: 1), Chair(column: 13, row: 'G', status: 1), Chair(column: 14, row: 'G', status: 1), Chair(column: 15, row: 'G', status: 1),Chair(column: 16, row: 'G', status: 1),Chair(column: 17, row: 'G', status: 1),Chair(column: 18, row: 'G', status: 1),Chair(column: 19, row: 'G', status: 1),Chair(column: 20, row: 'G', status: 1),Chair(column: 21, row: 'G', status: 1),Chair(column: 22, row: 'G', status: 1),Chair(column: 23, row: 'G', status: 1),Chair(column: 24, row: 'G', status: 1),Chair(column: 25, row: 'G', status: 1), Chair(column: 0, row: 'G', status: 'G'),Chair(column: 26, row: 'G', status: 1), Chair(column: 27, row: 'G', status: 1), Chair(column: 28, row: 'G', status: 1), Chair(column: 29, row: 'G', status: 1), Chair(column: 30, row: 'G', status: 1), Chair(column: 31, row: 'G', status: 1),
      Chair(column: 1, row: 'H', status: 1),  Chair(column: 2, row: 'H', status: 1),  Chair(column: 3, row: 'H', status: 1),  Chair(column: 4, row: 'H', status: 1), Chair(column: 5, row: 'H', status: 1), Chair(column: 6, row: 'H', status: 1), Chair(column: 0, row: 'H', status: 'H'), Chair(column: 7, row: 'H', status: 1), Chair(column: 8, row: 'H', status: 1), Chair(column: 9, row: 'H', status: 1), Chair(column: 10, row: 'H', status: 1), Chair(column: 11, row: 'H', status: 1),Chair(column: 12, row: 'H', status: 1), Chair(column: 13, row: 'H', status: 1), Chair(column: 14, row: 'H', status: 1), Chair(column: 15, row: 'H', status: 1),Chair(column: 16, row: 'H', status: 1),Chair(column: 17, row: 'H', status: 1),Chair(column: 18, row: 'H', status: 1),Chair(column: 19, row: 'H', status: 1),Chair(column: 20, row: 'H', status: 1),Chair(column: 21, row: 'H', status: 1),Chair(column: 22, row: 'H', status: 1),Chair(column: 23, row: 'H', status: 1),Chair(column: 24, row: 'H', status: 1),Chair(column: 25, row: 'H', status: 1), Chair(column: 0, row: 'H', status: 'H'),Chair(column: 26, row: 'H', status: 1), Chair(column: 27, row: 'H', status: 1), Chair(column: 28, row: 'H', status: 1), Chair(column: 29, row: 'H', status: 1), Chair(column: 30, row: 'H', status: 1), Chair(column: 31, row: 'H', status: 1),
      Chair(column: 1, row: 'I', status: 1),  Chair(column: 2, row: 'I', status: 1),  Chair(column: 3, row: 'I', status: 1),  Chair(column: 4, row: 'I', status: 1), Chair(column: 5, row: 'I', status: 1), Chair(column: 6, row: 'I', status: 1), Chair(column: 0, row: 'I', status: 'I'), Chair(column: 7, row: 'I', status: 1), Chair(column: 8, row: 'I', status: 1), Chair(column: 9, row: 'I', status: 1), Chair(column: 10, row: 'I', status: 1), Chair(column: 11, row: 'I', status: 1),Chair(column: 12, row: 'I', status: 1), Chair(column: 13, row: 'I', status: 1), Chair(column: 14, row: 'I', status: 1), Chair(column: 15, row: 'I', status: 1),Chair(column: 16, row: 'I', status: 1),Chair(column: 17, row: 'I', status: 1),Chair(column: 18, row: 'I', status: 1),Chair(column: 19, row: 'I', status: 1),Chair(column: 20, row: 'I', status: 1),Chair(column: 21, row: 'I', status: 1),Chair(column: 22, row: 'I', status: 1),Chair(column: 23, row: 'I', status: 1),Chair(column: 24, row: 'I', status: 1),Chair(column: 25, row: 'I', status: 1), Chair(column: 0, row: 'I', status: 'I'),Chair(column: 26, row: 'I', status: 1), Chair(column: 27, row: 'I', status: 1), Chair(column: 28, row: 'I', status: 1), Chair(column: 29, row: 'I', status: 1), Chair(column: 30, row: 'I', status: 1), Chair(column: 31, row: 'I', status: 1),
      Chair(column: 1, row: 'J', status: 1),  Chair(column: 2, row: 'J', status: 1),  Chair(column: 3, row: 'J', status: 1),  Chair(column: 4, row: 'J', status: 1), Chair(column: 5, row: 'J', status: 1), Chair(column: 6, row: 'J', status: 1), Chair(column: 0, row: 'J', status: 'J'), Chair(column: 7, row: 'J', status: 1), Chair(column: 8, row: 'J', status: 1), Chair(column: 9, row: 'J', status: 1), Chair(column: 10, row: 'J', status: 1), Chair(column: 11, row: 'J', status: 1),Chair(column: 12, row: 'J', status: 1), Chair(column: 13, row: 'J', status: 1), Chair(column: 14, row: 'J', status: 1), Chair(column: 15, row: 'J', status: 1),Chair(column: 16, row: 'J', status: 1),Chair(column: 17, row: 'J', status: 1),Chair(column: 18, row: 'J', status: 1),Chair(column: 19, row: 'J', status: 1),Chair(column: 20, row: 'J', status: 1),Chair(column: 21, row: 'J', status: 1),Chair(column: 22, row: 'J', status: 1),Chair(column: 23, row: 'J', status: 1),Chair(column: 24, row: 'J', status: 1),Chair(column: 25, row: 'J', status: 1), Chair(column: 0, row: 'J', status: 'J'),Chair(column: 26, row: 'J', status: 1), Chair(column: 27, row: 'J', status: 1), Chair(column: 28, row: 'J', status: 1), Chair(column: 29, row: 'J', status: 1), Chair(column: 30, row: 'J', status: 1), Chair(column: 31, row: 'J', status: 1),
      Chair(column: 1, row: 'K', status: 1),  Chair(column: 2, row: 'K', status: 1),  Chair(column: 3, row: 'K', status: 1),  Chair(column: 4, row: 'K', status: 1), Chair(column: 5, row: 'K', status: 1), Chair(column: 6, row: 'K', status: 1), Chair(column: 0, row: 'K', status: 'K'), Chair(column: 7, row: 'K', status: 1), Chair(column: 8, row: 'K', status: 1), Chair(column: 9, row: 'K', status: 1), Chair(column: 10, row: 'K', status: 1), Chair(column: 11, row: 'K', status: 1),Chair(column: 12, row: 'K', status: 1), Chair(column: 13, row: 'K', status: 1), Chair(column: 14, row: 'K', status: 1), Chair(column: 15, row: 'K', status: 1),Chair(column: 16, row: 'K', status: 1),Chair(column: 17, row: 'K', status: 1),Chair(column: 18, row: 'K', status: 1),Chair(column: 19, row: 'K', status: 1),Chair(column: 20, row: 'K', status: 1),Chair(column: 21, row: 'K', status: 1),Chair(column: 22, row: 'K', status: 1),Chair(column: 23, row: 'K', status: 1),Chair(column: 24, row: 'K', status: 1),Chair(column: 25, row: 'K', status: 1), Chair(column: 0, row: 'K', status: 'K'),Chair(column: 26, row: 'K', status: 1), Chair(column: 27, row: 'K', status: 1), Chair(column: 28, row: 'K', status: 1), Chair(column: 29, row: 'K', status: 1), Chair(column: 30, row: 'K', status: 1), Chair(column: 31, row: 'K', status: 1),
      Chair(column: 1, row: '0', status: 0),  Chair(column: 2, row: '0', status: 0),  Chair(column: 3, row: '0', status: 0),  Chair(column: 4, row: '0', status: 0), Chair(column: 5, row: '0', status: 0), Chair(column: 6, row: '0', status: 0), Chair(column: 0, row: '0', status:  0), Chair(column: 7, row: '0', status: 0), Chair(column: 8, row: '0', status: 0), Chair(column: 9, row: '0', status: 0), Chair(column: 10, row: '0', status: 0), Chair(column: 11, row: '0', status: 0),Chair(column: 12, row: '0', status: 0), Chair(column: 13, row: '0', status: 0), Chair(column: 14, row: '0', status: 0), Chair(column: 15, row: '0', status: 0),Chair(column: 16, row: '0', status: 0),Chair(column: 17, row: '0', status: 0),Chair(column: 18, row: '0', status: 0),Chair(column: 19, row: '0', status: 0),Chair(column: 20, row: '0', status: 0),Chair(column: 21, row: '0', status: 0),Chair(column: 22, row: '0', status: 0),Chair(column: 23, row: '0', status: 0),Chair(column: 24, row: '0', status: 0),Chair(column: 25, row: '0', status: 0), Chair(column: 0, row: '0', status: 0),Chair(column: 26, row: '0', status: 0), Chair(column: 27, row: '0', status: 0), Chair(column: 28, row: '0', status: 0), Chair(column: 29, row: '0', status: 0), Chair(column: 30, row: '0', status: 0), Chair(column: 31, row: '0', status: 0),
      Chair(column: 1, row: 'L', status: 1),  Chair(column: 2, row: 'L', status: 1),  Chair(column: 3, row: 'L', status: 1),  Chair(column: 4, row: 'L', status: 1), Chair(column: 5, row: 'L', status: 1), Chair(column: 6, row: 'L', status: 1), Chair(column: 0, row: 'L', status: 'L'), Chair(column: 7, row: 'L', status: 1), Chair(column: 8, row: 'L', status: 1), Chair(column: 9, row: 'L', status: 1), Chair(column: 10, row: 'L', status: 1), Chair(column: 11, row: 'L', status: 1),Chair(column: 12, row: 'L', status: 1), Chair(column: 13, row: 'L', status: 1), Chair(column: 14, row: 'L', status: 1), Chair(column: 15, row: 'L', status: 1),Chair(column: 16, row: 'L', status: 1),Chair(column: 17, row: 'L', status: 1),Chair(column: 18, row: 'L', status: 1),Chair(column: 19, row: 'L', status: 1),Chair(column: 20, row: 'L', status: 1),Chair(column: 21, row: 'L', status: 1),Chair(column: 22, row: 'L', status: 1),Chair(column: 23, row: 'L', status: 1),Chair(column: 24, row: 'L', status: 1),Chair(column: 25, row: 'L', status: 1), Chair(column: 0, row: 'L', status: 'L'),Chair(column: 26, row: 'L', status: 1), Chair(column: 27, row: 'L', status: 1), Chair(column: 28, row: 'L', status: 1), Chair(column: 29, row: 'L', status: 1), Chair(column: 30, row: 'L', status: 1), Chair(column: 31, row: 'L', status: 1),
      Chair(column: 1, row: 'M', status: 1),  Chair(column: 2, row: 'M', status: 1),  Chair(column: 3, row: 'M', status: 1),  Chair(column: 4, row: 'M', status: 1), Chair(column: 5, row: 'M', status: 1), Chair(column: 6, row: 'M', status: 1), Chair(column: 0, row: 'M', status: 'M'), Chair(column: 7, row: 'M', status: 1), Chair(column: 8, row: 'M', status: 1), Chair(column: 9, row: 'M', status: 1), Chair(column: 10, row: 'M', status: 1), Chair(column: 11, row: 'M', status: 1),Chair(column: 12, row: 'M', status: 1), Chair(column: 13, row: 'M', status: 1), Chair(column: 14, row: 'M', status: 1), Chair(column: 15, row: 'M', status: 1),Chair(column: 16, row: 'M', status: 1),Chair(column: 17, row: 'M', status: 1),Chair(column: 18, row: 'M', status: 1),Chair(column: 19, row: 'M', status: 1),Chair(column: 20, row: 'M', status: 1),Chair(column: 21, row: 'M', status: 1),Chair(column: 22, row: 'M', status: 1),Chair(column: 23, row: 'M', status: 1),Chair(column: 24, row: 'M', status: 1),Chair(column: 25, row: 'M', status: 1), Chair(column: 0, row: 'M', status: 'M'),Chair(column: 26, row: 'M', status: 1), Chair(column: 27, row: 'M', status: 1), Chair(column: 28, row: 'M', status: 1), Chair(column: 29, row: 'M', status: 1), Chair(column: 30, row: 'M', status: 1), Chair(column: 31, row: 'M', status: 1),
      Chair(column: 1, row: 'N', status: 1),  Chair(column: 2, row: 'N', status: 1),  Chair(column: 3, row: 'N', status: 1),  Chair(column: 4, row: 'N', status: 1), Chair(column: 5, row: 'N', status: 1), Chair(column: 6, row: 'N', status: 1), Chair(column: 0, row: 'N', status: 'N'), Chair(column: 7, row: 'N', status: 1), Chair(column: 8, row: 'N', status: 1), Chair(column: 9, row: 'N', status: 1), Chair(column: 10, row: 'N', status: 1), Chair(column: 11, row: 'N', status: 1),Chair(column: 12, row: 'N', status: 1), Chair(column: 13, row: 'N', status: 1), Chair(column: 14, row: 'N', status: 1), Chair(column: 15, row: 'N', status: 1),Chair(column: 16, row: 'N', status: 1),Chair(column: 17, row: 'N', status: 1),Chair(column: 18, row: 'N', status: 1),Chair(column: 19, row: 'N', status: 1),Chair(column: 20, row: 'N', status: 1),Chair(column: 21, row: 'N', status: 1),Chair(column: 22, row: 'N', status: 1),Chair(column: 23, row: 'N', status: 1),Chair(column: 24, row: 'N', status: 1),Chair(column: 25, row: 'N', status: 1), Chair(column: 0, row: 'N', status: 'N'),Chair(column: 26, row: 'N', status: 1), Chair(column: 27, row: 'N', status: 1), Chair(column: 28, row: 'N', status: 1), Chair(column: 29, row: 'N', status: 1), Chair(column: 30, row: 'N', status: 1), Chair(column: 31, row: 'N', status: 1),
      Chair(column: 1, row: 'O', status: 1),  Chair(column: 2, row: 'O', status: 1),  Chair(column: 3, row: 'O', status: 1),  Chair(column: 4, row: 'O', status: 1), Chair(column: 5, row: 'O', status: 1), Chair(column: 6, row: 'O', status: 1), Chair(column: 0, row: 'O', status: 'O'), Chair(column: 7, row: 'O', status: 1), Chair(column: 8, row: 'O', status: 1), Chair(column: 9, row: 'O', status: 1), Chair(column: 10, row: 'O', status: 1), Chair(column: 11, row: 'O', status: 1),Chair(column: 12, row: 'O', status: 1), Chair(column: 13, row: 'O', status: 1), Chair(column: 14, row: 'O', status: 1), Chair(column: 15, row: 'O', status: 1),Chair(column: 16, row: 'O', status: 1),Chair(column: 17, row: 'O', status: 1),Chair(column: 18, row: 'O', status: 1),Chair(column: 19, row: 'O', status: 1),Chair(column: 20, row: 'O', status: 1),Chair(column: 21, row: 'O', status: 1),Chair(column: 22, row: 'O', status: 1),Chair(column: 23, row: 'O', status: 1),Chair(column: 24, row: 'O', status: 1),Chair(column: 25, row: 'O', status: 1), Chair(column: 0, row: 'O', status: 'O'),Chair(column: 26, row: 'O', status: 1), Chair(column: 27, row: 'O', status: 1), Chair(column: 28, row: 'O', status: 1), Chair(column: 29, row: 'O', status: 1), Chair(column: 30, row: 'O', status: 1), Chair(column: 31, row: 'O', status: 1),
      Chair(column: 1, row: 'P', status: 1),  Chair(column: 2, row: 'P', status: 1),  Chair(column: 3, row: 'P', status: 1),  Chair(column: 4, row: 'P', status: 1), Chair(column: 5, row: 'P', status: 1), Chair(column: 6, row: 'P', status: 1), Chair(column: 0, row: 'P', status: 'P'), Chair(column: 7, row: 'P', status: 1), Chair(column: 8, row: 'P', status: 1), Chair(column: 9, row: 'P', status: 1), Chair(column: 10, row: 'P', status: 1), Chair(column: 11, row: 'P', status: 1),Chair(column: 12, row: 'P', status: 1), Chair(column: 13, row: 'P', status: 1), Chair(column: 14, row: 'P', status: 1), Chair(column: 15, row: 'P', status: 1),Chair(column: 16, row: 'P', status: 1),Chair(column: 17, row: 'P', status: 1),Chair(column: 18, row: 'P', status: 1),Chair(column: 19, row: 'P', status: 1),Chair(column: 20, row: 'P', status: 1),Chair(column: 21, row: 'P', status: 1),Chair(column: 22, row: 'P', status: 1),Chair(column: 23, row: 'P', status: 1),Chair(column: 24, row: 'P', status: 1),Chair(column: 25, row: 'P', status: 1), Chair(column: 0, row: 'P', status: 'P'),Chair(column: 26, row: 'P', status: 1), Chair(column: 27, row: 'P', status: 1), Chair(column: 28, row: 'P', status: 1), Chair(column: 29, row: 'P', status: 1), Chair(column: 30, row: 'P', status: 1), Chair(column: 31, row: 'P', status: 1),
      Chair(column: 1, row: 'Q', status: 1),  Chair(column: 2, row: 'Q', status: 1),  Chair(column: 3, row: 'Q', status: 1),  Chair(column: 4, row: 'Q', status: 1), Chair(column: 5, row: 'Q', status: 1), Chair(column: 6, row: 'Q', status: 1), Chair(column: 0, row: 'Q', status: 'Q'), Chair(column: 7, row: 'Q', status: 1), Chair(column: 8, row: 'Q', status: 1), Chair(column: 9, row: 'Q', status: 1), Chair(column: 10, row: 'Q', status: 1), Chair(column: 11, row: 'Q', status: 1),Chair(column: 12, row: 'Q', status: 1), Chair(column: 13, row: 'Q', status: 1), Chair(column: 14, row: 'Q', status: 1), Chair(column: 15, row: 'Q', status: 1),Chair(column: 16, row: 'Q', status: 1),Chair(column: 17, row: 'Q', status: 1),Chair(column: 18, row: 'Q', status: 1),Chair(column: 19, row: 'Q', status: 1),Chair(column: 20, row: 'Q', status: 1),Chair(column: 21, row: 'Q', status: 1),Chair(column: 22, row: 'Q', status: 1),Chair(column: 23, row: 'Q', status: 1),Chair(column: 24, row: 'Q', status: 1),Chair(column: 25, row: 'Q', status: 1), Chair(column: 0, row: 'Q', status: 'Q'),Chair(column: 26, row: 'Q', status: 1), Chair(column: 27, row: 'Q', status: 1), Chair(column: 28, row: 'Q', status: 1), Chair(column: 29, row: 'Q', status: 1), Chair(column: 30, row: 'Q', status: 1), Chair(column: 31, row: 'Q', status: 1),
      Chair(column: 1, row: '0', status:'1'),  Chair(column: 2, row: '0', status: '2'),  Chair(column: 3, row: '0', status: '3'),  Chair(column: 4, row: '0', status: 4), Chair(column: 5, row: '0', status: 5), Chair(column: 6, row: '0', status: 6), Chair(column: 0, row: '0', status: 0), Chair(column: 7, row: '0', status: 7), Chair(column: 8, row: '0', status: 8), Chair(column: 9, row: '0', status: 9), Chair(column: 10, row: '0', status: 10), Chair(column: 11, row: '0', status: 11),Chair(column: 12, row: '0', status: 12), Chair(column: 13, row: '0', status: 13), Chair(column: 14, row: '0', status: 14), Chair(column: 15, row: '0', status: 15),Chair(column: 16, row: '0', status: 16),Chair(column: 17, row: '0', status: 7),Chair(column: 18, row: '0', status: 18),Chair(column: 19, row: '0', status: 19),Chair(column: 20, row: '0', status: 20),Chair(column: 21, row: '0', status: 21),Chair(column: 22, row: '0', status: 22),Chair(column: 23, row: '0', status: 23),Chair(column: 24, row: '0', status: 24),Chair(column: 25, row: '0', status: 25), Chair(column: 0, row: '0', status: 0),Chair(column: 26, row: '0', status: 26), Chair(column: 27, row: '0', status: 27), Chair(column: 28, row: '0', status: 28), Chair(column: 29, row: '0', status: 29), Chair(column: 30, row: '0', status: 30), Chair(column: 31, row: '0', status: 31),


    //   0, 0, 1, 1, 1, 1, 'A', 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 'A', 1, 1, 1, 1, 0, 0,
    //   1, 1, 1, 1, 1, 1, 'B', 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 'B', 1, 1, 1, 1, 1, 1,
    //   1, 1, 1, 1, 1, 1, 'C', 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 'C', 1, 1, 1, 1, 1, 1,
    //   1, 1, 1, 1, 1, 1, 'D', 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 'D', 1, 1, 1, 1, 1, 1,
    //   1, 1, 1, 1, 1, 1, 'E', 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 'E', 1, 1, 1, 1, 1, 1,
    //   1, 1, 1, 1, 1, 1, 'F', 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 'F', 1, 1, 1, 1, 1, 1,
    //   1, 1, 1, 1, 1, 1, 'G', 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 'G', 1, 1, 1, 1, 1, 1,
    //   1, 1, 1, 1, 1, 1, 'H', 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 'H', 1, 1, 1, 1, 1, 1,
    //   1, 1, 1, 1, 1, 1, 'I', 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 'I', 1, 1, 1, 1, 1, 1,
    //   1, 1, 1, 1, 1, 1, 'J', 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 'J', 1, 1, 1, 1, 1, 1,
    //   1, 1, 1, 1, 1, 1, 'K', 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 'K', 1, 1, 1, 1, 1, 1,
    //   0, 0, 0, 0, 0, 0,  0,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0,
    //   1, 1, 1, 1, 1, 1, 'L', 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 'L', 1, 1, 1, 1, 1, 1,
    //   1, 1, 1, 1, 1, 1, 'M', 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 'M', 1, 1, 1, 1, 1, 1,
    //   1, 1, 1, 1, 1, 1, 'N', 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 'N', 1, 1, 1, 1, 1, 1,
    //   1, 1, 1, 1, 1, 1, 'O', 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 'O', 1, 1, 1, 1, 1, 1,
    //   1, 1, 1, 1, 1, 1, 'P', 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 'P', 1, 1, 1, 1, 1, 1,
    //   1, 1, 1, 1, 1, 1, 'Q', 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 'Q', 1, 1, 1, 1, 1, 1,
    // '1', 2, 3, 4, 5, 6,  0,  7, 8, 9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,   0,26,27,28,29,30,31

    ];

    return chairs;
  }

  static List<Chair> type3() {

    List<Chair> chairs;
  
    chairs = [

      Chair(column: 1, row: 'A', status: 1), Chair(column: 2, row: 'A', status: 1),Chair(column: 3, row: 'A', status: 1),Chair(column: 4, row: 'A', status: 1),Chair(column: 0, row: 'A', status: 'A'),Chair(column: 5, row: 'A', status: 1),Chair(column: 6, row: 'A', status: 1),Chair(column: 7, row: 'A', status: 1),Chair(column: 8, row: 'A', status: 1),Chair(column: 9, row: 'A', status: 1),Chair(column: 10, row: 'A', status: 1),Chair(column: 0, row: 'A', status: 0),Chair(column: 11, row: 'A', status: 1),Chair(column: 12, row: 'A', status: 1),Chair(column: 13, row: 'A', status: 1),Chair(column: 14, row: 'A', status: 1),Chair(column: 15, row: 'A', status: 1),Chair(column: 16, row: 'A', status: 1),Chair(column: 0, row: 'A', status: 'A'),Chair(column: 17, row: 'A', status: 1),Chair(column: 18, row: 'A', status: 1),Chair(column: 19, row: 'A', status: 1),Chair(column: 20, row: 'A', status: 1),
      Chair(column: 1, row: 'B', status: 1), Chair(column: 2, row: 'B', status: 1),Chair(column: 3, row: 'B', status: 1),Chair(column: 4, row: 'B', status: 1),Chair(column: 0, row: 'B', status: 'B'),Chair(column: 5, row: 'B', status: 1),Chair(column: 6, row: 'B', status: 1),Chair(column: 7, row: 'B', status: 1),Chair(column: 8, row: 'B', status: 1),Chair(column: 9, row: 'B', status: 1),Chair(column: 10, row: 'B', status: 1),Chair(column: 0, row: 'B', status: 0),Chair(column: 11, row: 'B', status: 1),Chair(column: 12, row: 'B', status: 1),Chair(column: 13, row: 'B', status: 1),Chair(column: 14, row: 'B', status: 1),Chair(column: 15, row: 'B', status: 1),Chair(column: 16, row: 'B', status: 1),Chair(column: 0, row: 'B', status: 'B'),Chair(column: 17, row: 'B', status: 1),Chair(column: 18, row: 'B', status: 1),Chair(column: 19, row: 'B', status: 1),Chair(column: 20, row: 'B', status: 1),
      Chair(column: 1, row: 'C', status: 1), Chair(column: 2, row: 'C', status: 1),Chair(column: 3, row: 'C', status: 1),Chair(column: 4, row: 'C', status: 1),Chair(column: 0, row: 'C', status: 'C'),Chair(column: 5, row: 'C', status: 1),Chair(column: 6, row: 'C', status: 1),Chair(column: 7, row: 'C', status: 1),Chair(column: 8, row: 'C', status: 1),Chair(column: 9, row: 'C', status: 1),Chair(column: 10, row: 'C', status: 1),Chair(column: 0, row: 'C', status: 0),Chair(column: 11, row: 'C', status: 1),Chair(column: 12, row: 'C', status: 1),Chair(column: 13, row: 'C', status: 1),Chair(column: 14, row: 'C', status: 1),Chair(column: 15, row: 'C', status: 1),Chair(column: 16, row: 'C', status: 1),Chair(column: 0, row: 'C', status: 'C'),Chair(column: 17, row: 'C', status: 1),Chair(column: 18, row: 'C', status: 1),Chair(column: 19, row: 'C', status: 1),Chair(column: 20, row: 'C', status: 1),
      Chair(column: 1, row: 'D', status: 1), Chair(column: 2, row: 'D', status: 1),Chair(column: 3, row: 'D', status: 1),Chair(column: 4, row: 'D', status: 1),Chair(column: 0, row: 'D', status: 'D'),Chair(column: 5, row: 'D', status: 1),Chair(column: 6, row: 'D', status: 1),Chair(column: 7, row: 'D', status: 1),Chair(column: 8, row: 'D', status: 1),Chair(column: 9, row: 'D', status: 1),Chair(column: 10, row: 'D', status: 1),Chair(column: 0, row: 'D', status: 0),Chair(column: 11, row: 'D', status: 1),Chair(column: 12, row: 'D', status: 1),Chair(column: 13, row: 'D', status: 1),Chair(column: 14, row: 'D', status: 1),Chair(column: 15, row: 'D', status: 1),Chair(column: 16, row: 'D', status: 1),Chair(column: 0, row: 'D', status: 'D'),Chair(column: 17, row: 'D', status: 1),Chair(column: 18, row: 'D', status: 1),Chair(column: 19, row: 'D', status: 1),Chair(column: 20, row: 'D', status: 1),
      Chair(column: 1, row: 'E', status: 1), Chair(column: 2, row: 'E', status: 1),Chair(column: 3, row: 'E', status: 1),Chair(column: 4, row: 'E', status: 1),Chair(column: 0, row: 'E', status: 'E'),Chair(column: 5, row: 'E', status: 1),Chair(column: 6, row: 'E', status: 1),Chair(column: 7, row: 'E', status: 1),Chair(column: 8, row: 'E', status: 1),Chair(column: 9, row: 'E', status: 1),Chair(column: 10, row: 'E', status: 1),Chair(column: 0, row: 'E', status: 0),Chair(column: 11, row: 'E', status: 1),Chair(column: 12, row: 'E', status: 1),Chair(column: 13, row: 'E', status: 1),Chair(column: 14, row: 'E', status: 1),Chair(column: 15, row: 'E', status: 1),Chair(column: 16, row: 'E', status: 1),Chair(column: 0, row: 'E', status: 'E'),Chair(column: 17, row: 'E', status: 1),Chair(column: 18, row: 'E', status: 1),Chair(column: 19, row: 'E', status: 1),Chair(column: 20, row: 'E', status: 1),
      Chair(column: 1, row: 'F', status: 1), Chair(column: 2, row: 'F', status: 1),Chair(column: 3, row: 'F', status: 1),Chair(column: 4, row: 'F', status: 1),Chair(column: 0, row: 'F', status: 'F'),Chair(column: 5, row: 'F', status: 1),Chair(column: 6, row: 'F', status: 1),Chair(column: 7, row: 'F', status: 1),Chair(column: 8, row: 'F', status: 1),Chair(column: 9, row: 'F', status: 1),Chair(column: 10, row: 'F', status: 1),Chair(column: 0, row: 'F', status: 0),Chair(column: 11, row: 'F', status: 1),Chair(column: 12, row: 'F', status: 1),Chair(column: 13, row: 'F', status: 1),Chair(column: 14, row: 'F', status: 1),Chair(column: 15, row: 'F', status: 1),Chair(column: 16, row: 'F', status: 1),Chair(column: 0, row: 'F', status: 'F'),Chair(column: 17, row: 'F', status: 1),Chair(column: 18, row: 'F', status: 1),Chair(column: 19, row: 'F', status: 1),Chair(column: 20, row: 'F', status: 1),
      Chair(column: 1, row: 'G', status: 1), Chair(column: 2, row: 'G', status: 1),Chair(column: 3, row: 'G', status: 1),Chair(column: 4, row: 'G', status: 1),Chair(column: 0, row: 'G', status: 'G'),Chair(column: 5, row: 'G', status: 1),Chair(column: 6, row: 'G', status: 1),Chair(column: 7, row: 'G', status: 1),Chair(column: 8, row: 'G', status: 1),Chair(column: 9, row: 'G', status: 1),Chair(column: 10, row: 'G', status: 1),Chair(column: 0, row: 'G', status: 0),Chair(column: 11, row: 'G', status: 1),Chair(column: 12, row: 'G', status: 1),Chair(column: 13, row: 'G', status: 1),Chair(column: 14, row: 'G', status: 1),Chair(column: 15, row: 'G', status: 1),Chair(column: 16, row: 'G', status: 1),Chair(column: 0, row: 'G', status: 'G'),Chair(column: 17, row: 'G', status: 1),Chair(column: 18, row: 'G', status: 1),Chair(column: 19, row: 'G', status: 1),Chair(column: 20, row: 'G', status: 1),
      Chair(column: 1, row: 'H', status: 1), Chair(column: 2, row: 'H', status: 1),Chair(column: 3, row: 'H', status: 1),Chair(column: 4, row: 'H', status: 1),Chair(column: 0, row: 'H', status: 'H'),Chair(column: 5, row: 'H', status: 1),Chair(column: 6, row: 'H', status: 1),Chair(column: 7, row: 'H', status: 1),Chair(column: 8, row: 'H', status: 1),Chair(column: 9, row: 'H', status: 1),Chair(column: 10, row: 'H', status: 1),Chair(column: 0, row: 'H', status: 0),Chair(column: 11, row: 'H', status: 1),Chair(column: 12, row: 'H', status: 1),Chair(column: 13, row: 'H', status: 1),Chair(column: 14, row: 'H', status: 1),Chair(column: 15, row: 'H', status: 1),Chair(column: 16, row: 'H', status: 1),Chair(column: 0, row: 'H', status: 'H'),Chair(column: 17, row: 'H', status: 1),Chair(column: 18, row: 'H', status: 1),Chair(column: 19, row: 'H', status: 1),Chair(column: 20, row: 'H', status: 1),
      Chair(column: 1, row: 'I', status: 1), Chair(column: 2, row: 'I', status: 1),Chair(column: 3, row: 'I', status: 1),Chair(column: 4, row: 'I', status: 1),Chair(column: 0, row: 'I', status: 'I'),Chair(column: 5, row: 'I', status: 1),Chair(column: 6, row: 'I', status: 1),Chair(column: 7, row: 'I', status: 1),Chair(column: 8, row: 'I', status: 1),Chair(column: 9, row: 'I', status: 1),Chair(column: 10, row: 'I', status: 1),Chair(column: 0, row: 'I', status: 0),Chair(column: 11, row: 'I', status: 1),Chair(column: 12, row: 'I', status: 1),Chair(column: 13, row: 'I', status: 1),Chair(column: 14, row: 'I', status: 1),Chair(column: 15, row: 'I', status: 1),Chair(column: 16, row: 'I', status: 1),Chair(column: 0, row: 'I', status: 'I'),Chair(column: 17, row: 'I', status: 1),Chair(column: 18, row: 'I', status: 1),Chair(column: 19, row: 'I', status: 1),Chair(column: 20, row: 'I', status: 1),
      Chair(column: 1, row: 'J', status: 1), Chair(column: 2, row: 'J', status: 1),Chair(column: 3, row: 'J', status: 1),Chair(column: 4, row: 'J', status: 1),Chair(column: 0, row: 'J', status: 'J'),Chair(column: 5, row: 'J', status: 1),Chair(column: 6, row: 'J', status: 1),Chair(column: 7, row: 'J', status: 1),Chair(column: 8, row: 'J', status: 1),Chair(column: 9, row: 'J', status: 1),Chair(column: 10, row: 'J', status: 1),Chair(column: 0, row: 'J', status: 0),Chair(column: 11, row: 'J', status: 1),Chair(column: 12, row: 'J', status: 1),Chair(column: 13, row: 'J', status: 1),Chair(column: 14, row: 'J', status: 1),Chair(column: 15, row: 'J', status: 1),Chair(column: 16, row: 'J', status: 1),Chair(column: 0, row: 'J', status: 'J'),Chair(column: 17, row: 'J', status: 1),Chair(column: 18, row: 'J', status: 1),Chair(column: 19, row: 'J', status: 1),Chair(column: 20, row: 'J', status: 1),
      Chair(column: 1, row: 'K', status: 1), Chair(column: 2, row: 'K', status: 1),Chair(column: 3, row: 'K', status: 1),Chair(column: 4, row: 'K', status: 1),Chair(column: 0, row: 'K', status: 'K'),Chair(column: 5, row: 'K', status: 1),Chair(column: 6, row: 'K', status: 1),Chair(column: 7, row: 'K', status: 1),Chair(column: 8, row: 'K', status: 1),Chair(column: 9, row: 'K', status: 1),Chair(column: 10, row: 'K', status: 1),Chair(column: 0, row: 'K', status: 0),Chair(column: 11, row: 'K', status: 1),Chair(column: 12, row: 'K', status: 1),Chair(column: 13, row: 'K', status: 1),Chair(column: 14, row: 'K', status: 1),Chair(column: 15, row: 'K', status: 1),Chair(column: 16, row: 'K', status: 1),Chair(column: 0, row: 'K', status: 'K'),Chair(column: 17, row: 'K', status: 1),Chair(column: 18, row: 'K', status: 1),Chair(column: 19, row: 'K', status: 1),Chair(column: 20, row: 'K', status: 1),
      Chair(column: 1, row: 'K', status: '1'), Chair(column: 2, row: 'K', status: '2'),Chair(column: 3, row: 'K', status: '3'),Chair(column: 4, row: 'K', status: 4),Chair(column: 0, row: 'K', status: 0),Chair(column: 5, row: 'K', status: 5),Chair(column: 6, row: 'K', status: 6),Chair(column: 7, row: 'K', status: 7),Chair(column: 8, row: 'K', status: 8),Chair(column: 9, row: 'K', status: 9),Chair(column: 10, row: 'K', status: 10),Chair(column: 0, row: 'K', status: 0),Chair(column: 11, row: 'K', status: 11),Chair(column: 12, row: 'K', status: 12),Chair(column: 13, row: 'K', status: 13),Chair(column: 14, row: 'K', status: 14),Chair(column: 15, row: 'K', status: 15),Chair(column: 16, row: 'K', status: 16),Chair(column: 0, row: 'K', status: 0),Chair(column: 17, row: 'K', status: 17),Chair(column: 18, row: 'K', status: 18),Chair(column: 19, row: 'K', status: 19),Chair(column: 20, row: 'K', status: 20),


    //   1, 1, 1, 1, 'A', 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 'A', 1, 1, 1, 1,
    //   1, 1, 1, 1, 'B', 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 'B', 1, 1, 1, 1,
    //   1, 1, 1, 1, 'C', 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 'C', 1, 1, 1, 1,
    //   1, 1, 1, 1, 'D', 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 'D', 1, 1, 1, 1,
    //   1, 1, 1, 1, 'E', 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 'E', 1, 1, 1, 1,
    //   1, 1, 1, 1, 'F', 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 'F', 1, 1, 1, 1,
    //   1, 1, 1, 1, 'G', 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 'G', 1, 1, 1, 1,
    //   1, 1, 1, 1, 'H', 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 'H', 1, 1, 1, 1,
    //   1, 1, 1, 1, 'I', 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 'I', 1, 1, 1, 1,
    //   1, 1, 1, 1, 'J', 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 'J', 1, 1, 1, 1,
    //   1, 1, 1, 1, 'K', 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 'K', 1, 1, 1, 1,
    // '1', 2, 3, 4,   0, 5, 6, 7, 8, 9,10, 0,11,12,13,14,15,16,   0,17,18,19,20
    ];

    return chairs;
  }

  

}